In [92]:
import torch
torch.__version__

'2.2.1+cpu'

In [93]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [94]:
# Checking the dimensions of a tensor using ndim
scalar.ndim

0

In [95]:
# We can get the number within a Tensor using item() for 0-dimensional tensors
scalar.item()

7

In [96]:
# Now let's look at vectors, where a vector is a single dimension tensor
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [97]:
# Checking the dimension of the vector, should be 1.
vector.ndim

1

In [98]:
# We can check the shape of a tensor with the .shape function
vector.shape

torch.Size([2])

In [99]:
# Let's look at a matrix now:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [100]:
# Matrices are as flexible as vectors, just with one extra dimension.
# Let's check the dimensionality again, should be 2 now.
MATRIX.ndim

2

In [101]:
# Now let's look at the shape, it's a 2x2 so...
MATRIX.shape

torch.Size([2, 2])

In [102]:
# Now let's create a tensor (although a tensor can represent almost anything)
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [103]:
# Let's check the dimensionality again, should be 3
TENSOR.ndim

3

In [104]:
# Let's check the shape. The dimensions go from outer to inner.
# It has 1 dimension of 3 by 3 so:
TENSOR.shape

torch.Size([1, 3, 3])

To summarize, a tensor is a n-dimensional array of numbers. 0-dimensional tensor is a scalar, 1-dimensional tensor is a vector, 2-dimensional tensor is a matrix.

In [105]:
# We can create a tensor filled with random values of size (3,4)
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.1592, 0.5585, 0.7851, 0.0329],
         [0.9231, 0.9967, 0.0342, 0.6473],
         [0.4587, 0.1659, 0.7269, 0.3543]]),
 torch.float32)

In [106]:
# The flexibility of torch.rand() is that we can adjust the size to whatever we want.
# So, a common image shape of [224, 224, 3] would be the following:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [107]:
# We can also fill a tensor with zeros through torch.zeros(). 
# This is often done for letting know that these should not be learned.
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [108]:
# We can do the same but then for ones with torch.ones()
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [109]:
# We can create a range in a tensor with torch.arange(start, end, step)
# For example, a tensor with numbers ranging from 0 to 10:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
# We can also create a tensor with a shape that's similar to another arbitrary tensor:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [111]:
# We can create some tensors with specific datatypes by using dtype
# The default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # defaults to float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # If True, operations on this tensor are recorded
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

Common mistakes are shape issues (that tensor shapes don't match up).
Other common mistakes are datatype and device issues.

In [112]:
# Let's create a tensor with dtype float16
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # or use torch.half
float_16_tensor.dtype

torch.float16

It is improtant to know how to get information from tensors.
Common attributes are:
1. shape - what shape is the tensor?
2. dtype - what datatype are the elements within the tensor stored in?
3. device - what device is the tensor stored on? (usually GPU or CPU)

In [113]:
# Let's test this for a random tensor
some_tensor = torch.rand(3,4)

# Find out some details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.0499, 0.6257, 0.0403, 0.9301],
        [0.9557, 0.3143, 0.0426, 0.0733],
        [0.9959, 0.0860, 0.3763, 0.8411]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [114]:
# Let's do some basic tensor operations like addition, subtraction, and multiplication.
tensor = torch.tensor([1, 2, 3])
# Let's add 10
tensor + 10

tensor([11, 12, 13])

In [115]:
# Let's multiply by 10
tensor * 10

tensor([10, 20, 30])

In [116]:
# Tensor values don't change unless they're reassigned, so what is tensor?
tensor

tensor([1, 2, 3])

In [117]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [118]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [119]:
# There are also some built-in functions for basic operations
# For multiplication there is torch.mul()
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [120]:
# For Addition there is torch.add()
torch.add(tensor, 10)

tensor([11, 12, 13])

In [121]:
# The original tensor stays the same
tensor

tensor([1, 2, 3])

In [122]:
# It's more common to use the symbols though:
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


Matrix multiplication is very common in ML and DL algorithms.

We can use torch.matmul() or simply use the @ operator.

Two rules that we must watch out for is that the inner dimensions must match and the resulting matrix has the shape of the outer dimensions

In [123]:
# Let's create a tensor and perform (matrix) multiplication:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [124]:
# element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [125]:
# Matrix multiplication
torch.matmul(tensor, tensor) # or use tensor @ tensor but torch.matmul() has more functionality

tensor(14)

In [126]:
# %%timeit # For average run time
# The torch.matmul() method is faster so use than with a loop:
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
value

27.6 µs ± 838 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [127]:
# %%timeit
tensor @ tensor

1.91 µs ± 10.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [128]:
# %%timeit
torch.matmul(tensor, tensor)

1.91 µs ± 41.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [ ]:
# One of the most common errors is shape mismatches.
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

We can make this matrix multiplication work by transposing (switching the dimensions of a given tensor).

We can do this either with torch.transpose(input, dim0, dim1), where input is the desired tensor and dim0 and dim1 are the dimensions to be swapped. 

Or, we do tensor.T, where tensor is transposed.


In [130]:
# view tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [131]:
# view tensor_A and transpose B
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [136]:
# Previously when doing the matrix multiplication we had a shape issue, now it should work
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")
print(f"\nDimensions from resulting matrix are the outer dimensions from the original tensors")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])

Dimensions from resulting matrix are the outer dimensions from the original tensors


In [137]:
# We can also use torch.mm() as a shortcut for torch.matmul()
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])