In [2]:
import torch
torch.__version__

c:\Users\alexa\Documents\Uni\Personal Projects\Pytorch-Fundamentals\Pytorch-Course\Lib\site-packages\torch\nn\modules\transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),


'2.2.1+cpu'

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# Checking the dimensions of a tensor using ndim
scalar.ndim

0

In [5]:
# We can get the number within a Tensor using item() for 0-dimensional tensors
scalar.item()

7

In [6]:
# Now let's look at vectors, where a vector is a single dimension tensor
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
# Checking the dimension of the vector, should be 1.
vector.ndim

1

In [8]:
# We can check the shape of a tensor with the .shape function
vector.shape

torch.Size([2])

In [9]:
# Let's look at a matrix now:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
# Matrices are as flexible as vectors, just with one extra dimension.
# Let's check the dimensionality again, should be 2 now.
MATRIX.ndim

2

In [12]:
# Now let's look at the shape, it's a 2x2 so...
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Now let's create a tensor (although a tensor can represent almost anything)
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
# Let's check the dimensionality again, should be 3
TENSOR.ndim

3

In [15]:
# Let's check the shape. The dimensions go from outer to inner.
# It has 1 dimension of 3 by 3 so:
TENSOR.shape

torch.Size([1, 3, 3])

To summarize, a tensor is a n-dimensional array of numbers. 0-dimensional tensor is a scalar, 1-dimensional tensor is a vector, 2-dimensional tensor is a matrix.

In [16]:
# We can create a tensor filled with random values of size (3,4)
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[5.6154e-01, 3.2087e-01, 6.9772e-02, 9.5582e-01],
         [7.0298e-01, 7.0857e-01, 9.0183e-01, 2.0034e-02],
         [3.0680e-01, 9.7961e-01, 6.5464e-01, 2.0754e-04]]),
 torch.float32)

In [17]:
# The flexibility of torch.rand() is that we can adjust the size to whatever we want.
# So, a common image shape of [224, 224, 3] would be the following:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [18]:
# We can also fill a tensor with zeros through torch.zeros(). 
# This is often done for letting know that these should not be learned.
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [19]:
# We can do the same but then for ones with torch.ones()
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [20]:
# We can create a range in a tensor with torch.arange(start, end, step)
# For example, a tensor with numbers ranging from 0 to 10:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# We can also create a tensor with a shape that's similar to another arbitrary tensor:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
# We can create some tensors with specific datatypes by using dtype
# The default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # defaults to float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # If True, operations on this tensor are recorded
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

Common mistakes are shape issues (that tensor shapes don't match up).
Other common mistakes are datatype and device issues.

In [23]:
# Let's create a tensor with dtype float16
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # or use torch.half
float_16_tensor.dtype

torch.float16

It is improtant to know how to get information from tensors.
Common attributes are:
1. shape - what shape is the tensor?
2. dtype - what datatype are the elements within the tensor stored in?
3. device - what device is the tensor stored on? (usually GPU or CPU)

In [24]:
# Let's test this for a random tensor
some_tensor = torch.rand(3,4)

# Find out some details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.1893, 0.5289, 0.5615, 0.2160],
        [0.7189, 0.2180, 0.8572, 0.3436],
        [0.0445, 0.6336, 0.9610, 0.8900]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [25]:
# Let's do some basic tensor operations like addition, subtraction, and multiplication.
tensor = torch.tensor([1, 2, 3])
# Let's add 10
tensor + 10

tensor([11, 12, 13])

In [26]:
# Let's multiply by 10
tensor * 10

tensor([10, 20, 30])

In [27]:
# Tensor values don't change unless they're reassigned, so what is tensor?
tensor

tensor([1, 2, 3])

In [28]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [29]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [30]:
# There are also some built-in functions for basic operations
# For multiplication there is torch.mul()
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [32]:
# For Addition there is torch.add()
torch.add(tensor, 10)

tensor([11, 12, 13])

In [33]:
# The original tensor stays the same
tensor

tensor([1, 2, 3])

In [34]:
# It's more common to use the symbols though:
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
